name: unniTel
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  hexcolor: ^1.0.4
  google_fonts: ^0.3.5
  email_validator: '^1.0.0'
  fluttertoast: ^7.0.2
  flutter_statusbarcolor: ^0.2.3
  flutter_verification_code: ^0.2.0
  syncfusion_flutter_gauges: ^1.0.0-beta
  kf_drawer: ^1.1.2
  class_builder: ^1.0.1
  font_awesome_flutter: ^8.8.1
  country_code_picker: ^1.4.0
  image_picker: ^0.6.7+4
  fdottedline: ^1.0.1
  http: ^0.12.2
  shared_preferences: ^0.5.10
  decimal: ^0.3.0
  intl: ^0.16.1


  


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/img_logo_unnitel.png
     - assets/images/google_icon.png
     - assets/images/home_logo.png
     - assets/images/menu_icon.png
     - assets/images/settings_icon.png
     - assets/images/wifi_icon.png
     - assets/images/down_arrow_icon.png
     - assets/images/wifi_icon2.png
     - assets/images/battery_icon.png
     - assets/images/usa_icon.png
     - assets/images/blue_icon.png
     - assets/images/pink_icon.png
     - assets/images/yellow_icon.png
     - assets/images/green_icon.png
     - assets/images/footer_logo.png
     - assets/images/edit_icon.png
     - assets/images/camera_icon.png
     - assets/images/mask_icon.png
     - assets/images/notification_icon.png
     - assets/images/change_part_icon.png
     - assets/images/help_icon.png
     - assets/images/manage_device.png
     - assets/images/change_pass_icon.png
     - assets/images/logouts_icon.png
     - assets/images/atrate_icon.png
     - assets/images/data_remianing_icon.png
     - assets/images/battery_icon.png
     - assets/images/congrulation_bg.png
     - assets/images/bubble_icon.png
     - assets/images/package_icon.png
     - assets/images/sg-flag-icon.png
     - assets/images/wifi_connected.png
     - assets/images/wifi_notConnected.png
     - assets/images/default-flag-icon.png
     - assets/images/battery-icon.png























  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
